services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: "mongodb://inkpos:1nkp05@mongo:27017/inkpos_db?authSource=admin"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: inkpos
      MONGO_INITDB_ROOT_PASSWORD: 1nkp05
      MONGO_INITDB_DATABASE: inkpos_db
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: inkpos
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1nkp05
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1nkp05
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
